
export const dummyMembers: any[] = [
    {
        _id: '1',
        createdAt: '2023-05-05',
        memberName: 'Ariana Morrow',
        patientId: '5326086967',
        dateOfBirth: '',
        typeOfRegister: 'Patient',
        registeredBy: '',
        hospitalName: '',
    },
    {
        _id: '2',
        createdAt: '2023-06-10',
        memberName: 'James Carter',
        patientId: '6543219870',
        dateOfBirth: '1990-04-12',
        typeOfRegister: 'Patient',
        registeredBy: 'Admin',
        hospitalName: 'City Hospital',
    },
    {
        _id: '3',
        createdAt: '2023-06-15',
        memberName: 'Sophia Williams',
        patientId: '9876543210',
        dateOfBirth: '',
        typeOfRegister: 'Doctor',
        registeredBy: 'Super Admin',
        hospitalName: 'General Hospital',
    },
    {
        _id: '4',
        createdAt: '2023-07-01',
        memberName: 'Liam Smith',
        patientId: '1122334455',
        dateOfBirth: '1988-02-28',
        typeOfRegister: 'Patient',
        registeredBy: 'Admin',
        hospitalName: '',
    },
    {
        _id: '5',
        createdAt: '2023-07-05',
        memberName: 'Olivia Johnson',
        patientId: '2233445566',
        dateOfBirth: '',
        typeOfRegister: 'Nurse',
        registeredBy: 'Super Admin',
        hospitalName: 'Wellness Center',
    },
    {
        _id: '6',
        createdAt: '2023-08-12',
        memberName: 'Noah Brown',
        patientId: '3344556677',
        dateOfBirth: '',
        typeOfRegister: 'Patient',
        registeredBy: '',
        hospitalName: '',
    },
    {
        _id: '7',
        createdAt: '2023-08-20',
        memberName: 'Emma Davis',
        patientId: '4455667788',
        dateOfBirth: '1995-06-18',
        typeOfRegister: 'Patient',
        registeredBy: 'Admin',
        hospitalName: 'Sunrise Hospital',
    },
    {
        _id: '8',
        createdAt: '2023-09-01',
        memberName: 'William Martinez',
        patientId: '5566778899',
        dateOfBirth: '',
        typeOfRegister: 'Doctor',
        registeredBy: '',
        hospitalName: '',
    },
    {
        _id: '9',
        createdAt: '2023-09-10',
        memberName: 'Isabella Garcia',
        patientId: '6677889900',
        dateOfBirth: '',
        typeOfRegister: 'Patient',
        registeredBy: 'Super Admin',
        hospitalName: 'Metro Clinic',
    },
    {
        _id: '10',
        createdAt: '2023-09-15',
        memberName: 'Ethan Wilson',
        patientId: '7788990011',
        dateOfBirth: '',
        typeOfRegister: 'Nurse',
        registeredBy: 'Admin',
        hospitalName: '',
    },
    {
        _id: '11',
        createdAt: '2023-09-18',
        memberName: 'Mia Anderson',
        patientId: '8899001122',
        dateOfBirth: '',
        typeOfRegister: 'Patient',
        registeredBy: '',
        hospitalName: 'Central Hospital',
    },
    {
        _id: '12',
        createdAt: '2023-09-20',
        memberName: 'Lucas Thomas',
        patientId: '9900112233',
        dateOfBirth: '',
        typeOfRegister: 'Patient',
        registeredBy: 'Super Admin',
        hospitalName: '',
    },
    {
        _id: '13',
        createdAt: '2023-09-25',
        memberName: 'Charlotte Taylor',
        patientId: '0011223344',
        dateOfBirth: '',
        typeOfRegister: 'Doctor',
        registeredBy: '',
        hospitalName: 'LifeCare Hospital',
    },
    {
        _id: '14',
        createdAt: '2023-10-01',
        memberName: 'Henry Moore',
        patientId: '1122334466',
        dateOfBirth: '',
        typeOfRegister: 'Patient',
        registeredBy: 'Admin',
        hospitalName: '',
    },
    {
        _id: '15',
        createdAt: '2023-10-05',
        memberName: 'Amelia White',
        patientId: '2233445577',
        dateOfBirth: '',
        typeOfRegister: 'Nurse',
        registeredBy: '',
        hospitalName: '',
    },
];


export const hospitalOptions = [
    "Lagos University Teaching Hospital",
    "National Hospital Abuja",
    "Aminu Kano Teaching Hospital",
    "University of Benin Teaching Hospital",
    "Obafemi Awolowo University Teaching Hospital",
    "University College Hospital Ibadan",
    "Ahmadu Bello University Teaching Hospital",
    "Federal Medical Centre Abeokuta",
    "Federal Medical Centre Owerri",
];


export const insuranceOptions = [
    "AXA Mansard",
    "Hygeia HMO",
    "Reliance HMO",
    "Avon HMO",
    "Leadway Health",
    "Total Health Trust",
    "Clearline HMO",
    "Mediplan Healthcare",
    "Greenbay HMO",
];

export const stateOptions = [
    "Lagos",
    "Abuja (FCT)",
    "Kano",
    "Ogun",
    "Rivers",
    "Kaduna",
    "Enugu",
    "Oyo",
    "Anambra",
    "Bauchi",
];

export const lgaOptions = [
    "Ikeja",
    "Surulere",
    "Eti-Osa",
    "Mushin",
    "Agege",
    "Kosofe",
    "Epe",
    "Ikorodu",
    "Badagry",
    "Oshodi-Isolo",
];

// Date of Birth dropdowns
export const days = Array.from({ length: 31 }, (_, i) => String(i + 1).padStart(2, "0"));
export const months = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
];
export const years = Array.from({ length: 100 }, (_, i) => String(new Date().getFullYear() - i));